on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: manna-harbour/miryoku_zmk/.github/workflows/main.yml@master
    with:
      board: '["nice_nano_v2"]'
      shield: '["anywhy_flake_left","anywhy_flake_right, settings_reset"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE #define MIRYOKU_CLIPBOARD_WIN #define MIRYOKU_KLUDGE_TAPDELAY, #define MIRYOKU_KLUDGE_SOFT_OFF, #define MIRYOKU_KLUDGE_TAPDELAY, #define MIRYOKU_KLUDGE_THUMBCOMBOS"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y CONFIG_ZMK_POINTING=y"]'
