# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build anywhy_flake with nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["anywhy_flake_left","anywhy_flake_right"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE  #define MIRYOKU_KLUDGE_TAPDELAY"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y  CONFIG_ZMK_POINTING=y"]'
