    uses: manna-harbour/miryoku_zmk/.github/workflows/main.yml@master
    with:
      board: '["nice_nano_v2"]'
      shield: '["anywhy_flake_left","anywhy_flake_right"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE #define MIRYOKU_CLIPBOARD_WIN #define MIRYOKU_KLUDGE_SOFT_OFF #define MIRYOKU_KLUDGE_TAPDELAY"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y CONFIG_ZMK_PM_SOFT_OFF=y CONFIG_ZMK_POINTING=y"]'
