name: 'Build anywhy_flake'
on: workflow_dispatch
jobs:
  build:
    uses: manna-harbour/miryoku_zmk/.github/workflows/main.yml@master
    with:
      board: '["nice_nano_v2"]'
      shield: '["anywhy_flake_left","anywhy_flake_right"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE"]'
