on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: manna-harbour/miryoku_zmk/.github/workflows/main.yml@master
    with:
      board: '["nice_nano_v2"]'
      shield: '["anywhy_flake_left","anywhy_flake_right"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y CONFIG_ZMK_PM_SOFT_OFF=y CONFIG_ZMK_POINTING=y"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE"]'
      
