name: Build Anywhy Flake (nice!nano v2)

on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: code-guerilla/miryoku_zmk/.github/workflows/main.yml@master
    with:
      board: '["nice_nano"]'
      shield: '["anywhy_flake_left","anywhy_flake_right"]'
      custom_config: '["#define MIRYOKU_KEYBOARD_ANYWHY_FLAKE\n#define MIRYOKU_CLIPBOARD_WIN\n#define MIRYOKU_KLUDGE_TAPDELAY"]'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y\nCONFIG_ZMK_POINTING=y"]'